// Writes docs/TABLE_FORMATS.md from tests/column_formats.js (run: npm run formats).
const fs = require('fs');
const path = require('path');
const { FORMATS, NUMBER_FORMATS } = require('./column_formats');

const LABEL = {
  rupee: 'Indian rupee',
  rupee_paise: 'Indian rupee, 2 decimals',
  percent: 'Percent',
  count: 'Indian number (no ₹)',
  quantity: 'Automatic',
  date: 'Date',
};
const ORDER = ['rupee', 'rupee_paise', 'percent', 'count', 'quantity', 'date'];

const lines = [];
const add = (...l) => lines.push(...l);
add('# Table column formats (Google Sheets)', '',
  'Every output tab is a native Google Sheets **Table**, and the Table owns the formatting: the pipeline writes plain values only and never sets a number or date format. This page lists which columns need which format. Set them once; the pipeline keeps them on every run.', '',
  '> Generated by `npm run formats` from `tests/column_formats.js`. A test fails if an output column is missing from that list, so this page cannot go out of date silently.', '',
  '## How to set a format', '',
  '- **Date** columns: select the column → Format → Number → Date (or set the Table column type to *Date*).',
  '- **Percent** columns: Format → Number → Percent (or Table column type *Percent*). The values are stored as fractions (0.08 shows as 8%).',
  '- **Indian rupee / Indian number** columns: select the column → Format → Number → **Custom number format** → paste the format below → Apply.',
  '- Select a whole column at a time. The header row is not affected.', '',
  '## Custom number formats', '',
  '| Use for | Paste this |', '|---|---|',
  `| Indian rupee (whole rupees) | \`${NUMBER_FORMATS.rupee}\` |`,
  `| Indian rupee with paise (cost per beneficiary) | \`${NUMBER_FORMATS.rupee_paise}\` |`,
  `| Indian number, no ₹ (counts, beneficiaries) | \`${NUMBER_FORMATS.count}\` |`,
  `| Percent | \`${NUMBER_FORMATS.percent}\` (or the built-in Percent format) |`,
  `| Date | \`${NUMBER_FORMATS.date}\` (or any date format you prefer) |`, '',
  '**How the Indian format works:** it has a rule for amounts of one crore or more, one for one lakh or more, and a default. The digits are grouped in twos after the first three (₹8,60,00,000; ₹7,50,000; ₹96,000).', '',
  '**Limits to know:**',
  '- A custom format can have only two conditions, so a **negative** amount is shown with Western grouping (-₹9,675,000). Only the balances in `fct4_budget_year` can be negative (when commitments exceed the budget).',
  '- Amounts of **₹100 crore or more** (10 digits) show the first group with three digits (₹123,45,67,890 instead of ₹1,23,45,67,890). Below that the grouping is exactly Indian.',
  '- Optional, untested: File → Settings → Locale = **India** may make Sheets group lakh/crore in the built-in Rupee format, including for negatives.',
  '- These formats change only how the Sheet looks. Looker Studio reads the underlying numbers and applies its own formatting (the dashboard has Indian-rupee text fields).',
  '- `quantity` columns hold a fraction when the outcome target is a percentage (0.7 = 70%) and a plain count otherwise, so leave them on Automatic.', '',
  '## Columns to format, tab by tab', '');
Object.entries(FORMATS).forEach(([tab, groups]) => {
  const cols = ORDER.filter((k) => groups[k] && groups[k].length);
  if (!cols.length) return;
  add(`### \`${tab}\``, '', '| Column | Format |', '|---|---|');
  cols.forEach((k) => groups[k].forEach((c) => add(`| \`${c}\` | ${LABEL[k]} |`)));
  add('');
});
add('Tabs not listed here (`stg_outcome_progress`, `stg_support`, `stg_maturity`, `fct3_support_activity`, `fct5_maturity_rag`, `fct6_grantee_annual_info` (its values are already display text), and the log / audit tabs) have no number or date columns to format.', '',
  '## Things to know about Tables', '',
  '- **Column types:** when a Table is created, Sheets guesses each column\'s type from its data. If a column that should hold dates or numbers was guessed as Text (for example because it was empty), change its type.',
  '- **New columns from time to time** (for example the ones added in pipeline v0.1.2: `fct2` +5, `fct3` +1, `fct5` +1) are written just to the right of an existing Table. Drag the Table\'s edge to include them; Looker Studio reads them either way.',
  '- **More rows than the Table has:** drag the Table\'s bottom edge. **Fewer rows:** the pipeline deletes the surplus rows itself.');
const out = path.join(__dirname, '..', 'docs', 'TABLE_FORMATS.md');
fs.writeFileSync(out, lines.join('\n') + '\n');
console.log('wrote', out);
